version: "3.1"
services:
postgres:
  image: postgres:12.1
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: ${DB_USER}
    POSTGRES_DB: ${DB_NAME}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
  volumes:
    - ./postgresql/data:/var/lib/postgresql/data

service:
  image:
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - /app/node_modules
    - ./service/config:/app/config
    - ./service/src:/app/src
    - ./service/test:/app/test
  ports:
    - "3000:3000"
clientimage:
  build:
    context: ./client
    dockerfile: Dockerfile.dev
  volumes:
    - /app/node_modules
    - ./ui:/app
  ports:
    - "8080:8080"
